### ISSUE TITLE
Problems with HDT v1.5.x due to MahApps.Metro upgrade.

### ISSUE THREAD

**Issue by azeier** [RedHatter/Graveyard#24]
With HDT v1.5.0 MahApps.Metro was updated to 1.5.0, which sadly breaks the settings button in your case.

```
7:26:51 PM|Error|PluginWrapper.OnButtonPress >> Graveyard
System.MissingMethodException: Method not found: 'Void MahApps.Metro.Controls.Flyout.set_Header(System.String)'.
   at HDT.Plugins.Graveyard.SettingsView.CreateSettingsFlyout()
   at HDT.Plugins.Graveyard.SettingsView.get_Flyout()
   at HDT.Plugins.Graveyard.GraveyardPlugin.OnButtonPress()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.OnButtonPress() in D:\GitHub\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 144
```

Original issue on HDT: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3453

**Comment by Dushku** [comment]
judge 2020 has released a fix here: https://github.com/RedHatter/Graveyard/pull/26

**Comment by RedHatter** [comment]
Merged Judge2020's fix.
